Tests return exit-code 1 if a test failed, 0 otherwise.

diff --git a/test/simple/testAll b/test/simple/testAll
--- a/test/simple/testAll
+++ b/test/simple/testAll
@@ -1,7 +1,17 @@
-bash testP
-bash testSE
-bash testTE
-bash testTh
-bash testC
-bash testSW
-bash testR
+#!/bin/sh
+
+/bin/sh testP  ; X1=$?
+/bin/sh testSE ; X2=$?
+/bin/sh testTE ; X3=$?
+/bin/sh testTh ; X4=$?
+/bin/sh testC  ; X5=$?
+/bin/sh testSW ; X6=$?
+/bin/sh testR  ; X7=$?
+
+TOTAL=$[$X1 + $X2 + $X3 + $X4 + $X5 + $X6 + $X7]
+echo "Total number of simple tests that failed: $TOTAL"
+
+if [ "$TOTAL" = "0" ];
+then exit 0
+else exit 1
+fi
diff --git a/test/testAll b/test/testAll
--- a/test/testAll
+++ b/test/testAll
@@ -1,14 +1,24 @@
+#!/bin/sh
+
 clear
 echo SIMPLE TEST. NO OVERLOADING
 cd simple
-bash testAll
+/bin/sh testAll; X0=$?
 cd ..
 echo OVERLOADING TEST SET
-bash testP
-bash testSE
-bash testTE
-bash testM
-bash testTh
-bash testC
-bash testSW
-bash testR
+/bin/sh testP  ; X1=$?
+/bin/sh testSE ; X2=$?
+/bin/sh testTE ; X3=$?
+/bin/sh testM  ; X4=$?
+/bin/sh testTh ; X5=$?
+/bin/sh testC  ; X6=$?
+/bin/sh testSW ; X7=$?
+/bin/sh testR  ; X8=$?
+
+TOTAL=$[$X0 + $X1 + $X2 + $X3 + $X4 + $X5 + $X6 + $X7 + $X8]
+echo "Test failures: $TOTAL"
+
+if [ "$TOTAL" = "0" ];
+then exit 0
+else exit 1
+fi
